# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

limao = Ingredient.create(name: "limao")
ice = Ingredient.create!(name: "ice")
cachaca = Ingredient.create!(name: "cachaca")
amora = Ingredient.create!(name: "amora")
soda = Ingredient.create!(name: "soda")
suco_de_limao = Ingredient.create!(name: "suco de limao")
frutas_vermelhas = Ingredient.create!(name: "frutas vermelhas")
licor_de_gengibre = Ingredient.create!(name: "licor de gengibre")
laranja = Ingredient.create!(name: "laranja")
cranberry = Ingredient.create!(name: "cranberry")
morango = Ingredient.create!(name: "morango")
folhas_de_manjericao = Ingredient.create!(name: "folhas de manjericao")
figo = Ingredient.create!(name: "figo")
pepino = Ingredient.create!(name: "pepino")
cerveja_de_gengibre = Ingredient.create!(name: "cerveja de gengibre")
pimenta_jalapeno = Ingredient.create!(name: "pimenta jalapeno")
nectar_de_agave = Ingredient.create!(name: "nectar de agave")
kiwi = Ingredient.create!(name: "kiwi")
mango = Ingredient.create!(name: "mango")
melancia = Ingredient.create!(name: "melancia")
acai = Ingredient.create!(name: "acai")

c1 = Cocktail.create!(name:"CAIPIRINHA DE MELÃO")
c2 = Cocktail.create!(name:"CAIPIRINHA DE FRUTAS VERMELHAS")
c3 = Cocktail.create!(name:"CAIPIRINHA DE MANGO")
c4 = Cocktail.create!(name:"CAIPIRINHA DA BOSSA")
c5 = Cocktail.create!(name:"CAIPIRINHA DE ACAI")
c6 = Cocktail.create!(name:"CAIPIRINHA DE FIGO")
c7 = Cocktail.create!(name:"CAIPIRINHA DE PEPINO")
c8 = Cocktail.create!(name:"CAIPIRINHA DE MELANCIA")
c9 = Cocktail.create!(name:"CAIPIRINHA DE MORANGO")
c10 = Cocktail.create!(name:"CAIPIRINHA DA VILA MADALENA")

## Dose.create!(cocktail: caipirinha, ingredient: lime, description: 'limão')
## Dose.create!(cocktail: caipirinha, ingredient: ice, description: 'gelo')
## Dose.create!(cocktail: caipirinha, ingredient: mé, description: 'pinga da boa')
## Dose.create!(cocktail: caipirinha, ingredient: sugar, description: 'açúcar')
## Dose.create!(cocktail: mojito, ingredient: lime, description: 'limão')
## Dose.create!(cocktail: mojito, ingredient: ice, description: 'gelo')
## Dose.create!(cocktail: mojito, ingredient: rum, description: 'rum do pirata')
Dose.create!(cocktail: mojito, ingredient: sugar, description: 'açúcar')
Dose.create!(cocktail: mojito, ingredient: mint, description: 'folhinha de hortelã')
